Vagrant.configure("2") do |config|

  config.vm.provider "vmware_desktop" do |v|
    v.memory = 2048
    v.cpus = 2
    v.gui = false
  end

  config.vm.define "ubuntu" do |ubuntu|
    ubuntu.vm.box = "spox/ubuntu-arm"
    ubuntu.vm.box_version = "1.0.0"
    ubuntu.vm.hostname = "ubuntu-server"
    ubuntu.vm.network "private_network", ip: "192.168.56.10"
    ubuntu.vm.network "forwarded_port", guest: 22, host: 2210, id: "ssh"
    ubuntu.vm.network "forwarded_port", guest: 80, host: 8010, id: "http"
  end

  config.vm.define "centos" do |centos|
    centos.vm.box = "gyptazy/rocky9.3-arm64"
    centos.vm.hostname = "centos-server"
    centos.vm.network "private_network", ip: "192.168.56.11"
    centos.vm.network "forwarded_port", guest: 22, host: 2211, id: "ssh"
    centos.vm.network "forwarded_port", guest: 80, host: 8011, id: "http"
  end
end
