Vagrant.configure("2") do |config|
  config.vm.box = "spox/ubuntu-arm"
  config.vm.box_version = "1.0.0"
  
  config.vm.provider "vmware_desktop" do |v|
    v.memory = 2048
    v.cpus = 2
    v.gui = false
  end

  config.vm.define "prod" do |prod|
    prod.vm.hostname = "prod-server"
    prod.vm.network "private_network", ip: "192.168.56.10"
    prod.vm.network "forwarded_port", guest: 22, host: 2210, id: "ssh"
  end

  config.vm.define "dev" do |dev|
    dev.vm.hostname = "dev-server"
    dev.vm.network "private_network", ip: "192.168.56.11"
    dev.vm.network "forwarded_port", guest: 22, host: 2211, id: "ssh"
  end
end
